User.destroy_all
State.destroy_all
departamentos = ['Amazonas',
'Antioquía',
'Arauca',
'Atlántico',
'Bolivar',
'Boyacá',
'Caldas',
'Caquetá',
'Casanare',
'Cauca',
'Cesar',
'Chocó',
'Córdoba',
'Cundinamarca',
'Guainía',
'Guaviare',		
'Huila',
'La Guajira',
'Magdalena',
'Meta',
'Nariño',
'Norte de Santander',
'Putumayo',
'Quindio',
'Risaralda',
'San Andrés y Providencia',
'Santander',
'Sucre',
'Tolima',
'Valle del Cauca',
'Vaupés',
'Vichada']

departamentos.each do |departamento|
  State.create(name: departamento, link_rewrite: departamento.downcase, created_at: Time.now, updated_at: Time.now)
end

ciudades = [
["Leticia - Amazonas"],
["Puerto Nariño - Amazonas"],
["Tarapaca - Amazonas"],
["La Chorrera - Amazonas"],
["Abejorral  - Antioquia"],
["Abriaquá - Antioquia"],
["Alejandría  - Antioquia"],
["Amagá - Antioquia"],
["Amalfi  - Antioquia"],
["Andes  - Antioquia"],
["Angelópolis  - Antioquia"],
["Angostura  - Antioquia"],
["Anorí - Antioquia"],
["Antioquia  - Antioquia"],
["Anzá - Antioquia"],
["Apartadó - Antioquia"],
["Arboletes  - Antioquia"],
["Argelia  - Antioquia"],
["Armenia  - Antioquia"],
["Barbosa  - Antioquia"],
["Bello  - Antioquia"],
["Belmira  - Antioquia"],
["Betania  - Antioquia"],
["Betulia  - Antioquia"],
["Bolívar  - Antioquia"],
["Briceño  - Antioquia"],
["Buriticá - Antioquia"],
["Cáceres  - Antioquia"],
["Caicedo  - Antioquia"],
["Caldas  - Antioquia"],
["Campamento  - Antioquia"],
["Cañasgordas  - Antioquia"],
["Caracolí - Antioquia"],
["Caramanta  - Antioquia"],
["Carepa  - Antioquia"],
["Carmen de Viboral  - Antioquia"],
["Carolina del Prí­ncipe  - Antioquia"],
["Caucasia  - Antioquia"],
["Chigorodó - Antioquia"],
["Cisneros  - Antioquia"],
["Cocorná - Antioquia"],
["Concepción  - Antioquia"],
["Concordia  - Antioquia"],
["Copacabana  - Antioquia"],
["Currulao  - Antioquia"],
["Dabeiba  - Antioquia"],
["Donmatías  - Antioquia"],
["Ebéjico  - Antioquia"],
["El Bagre  - Antioquia"],
["El Peñol  - Antioquia"],
["El Retiro  - Antioquia"],
["Entrerríos  - Antioquia"],
["Envigado  - Antioquia"],
["Fredonia  - Antioquia"],
["Frontino  - Antioquia"],
["Giraldo  - Antioquia"],
["Girardota  - Antioquia"],
["Gómez Plata  - Antioquia"],
["Granada  - Antioquia"],
["Guadalupe  - Antioquia"],
["Guarne  - Antioquia"],
["Guatapé - Antioquia"],
["Heliconia  - Antioquia"],
["Hispania  - Antioquia"],
["Itagui - Antioquia"],
["Ituango  - Antioquia"],
["Jardá­n  - Antioquia"],
["Jericó - Antioquia"],
["La Ceja  - Antioquia"],
["La Estrella  - Antioquia"],
["La Pintada  - Antioquia"],
["La Unión  - Antioquia"],
["Liborina  - Antioquia"],
["Maceo  - Antioquia"],
["Marinilla  - Antioquia"],
["Medellín - Antioquia"],
["Montebello  - Antioquia"],
["Murindó - Antioquia"],
["Mutatá - Antioquia"],
["Nariño  - Antioquia"],
["Nechí - Antioquia"],
["Necoclí - Antioquia"],
["Olaya  - Antioquia"],
["Peque  - Antioquia"],
["Pueblorrico  - Antioquia"],
["Puerto Berrío  - Antioquia"],
["Puerto Nare  - Antioquia"],
["Puerto Triunfo  - Antioquia"],
["Remedios  - Antioquia"],
["Rionegro  - Antioquia"],
["Sabanalarga  - Antioquia"],
["Sabaneta  - Antioquia"],
["Salgar  - Antioquia"],
["San Andrés de Cuerquia  - Antioquia"],
["San Carlos  - Antioquia"],
["San Francisco  - Antioquia"],
["San Jerónimo  - Antioquia"],
["San José de la Montaña  - Antioquia"],
["San Juan de Urabá - Antioquia"],
["San Luis  - Antioquia"],
["San Pedro de los Milagros  - Antioquia"],
["San Pedro de Urabá - Antioquia"],
["San Rafael  - Antioquia"],
["San Roque  - Antioquia"],
["San Vicente  - Antioquia"],
["Santa Bárbara  - Antioquia"],
["Santa Rosa de Osos  - Antioquia"],
["Santo Domingo  - Antioquia"],
["Santuario  - Antioquia"],
["Segovia  - Antioquia"],
["Sonsón  - Antioquia"],
["Sopetrán  - Antioquia"],
["Támesis  - Antioquia"],
["Tarazá - Antioquia"],
["Tarso  - Antioquia"],
["Titiribí - Antioquia"],
["Toledo  - Antioquia"],
["Turbo  - Antioquia"],
["Uramita  - Antioquia"],
["Urrao  - Antioquia"],
["Valdivia  - Antioquia"],
["Valparaí­so  - Antioquia"],
["Vegachí - Antioquia"],
["Venecia  - Antioquia"],
["Vigía del Fuerte  - Antioquia"],
["Yalí - Antioquia"],
["Yarumal  - Antioquia"],
["Yolombó - Antioquia"],
["Yondó - Antioquia"],
["Zaragoza  - Antioquia"],
["Doradal - Antioquia"],
["Puerto Boyaca - Antioquia"],
["Puerto Valdivia - Antioquia"],
["Santa Fe De Antioquia - Antioquia"],
["La Sierra - Antioquia"],
["Bajira - Antioquia"],
["Bolombolo - Antioquia"],
["Carmen de Atrato - Antioquia"],
["Ciudad Bolivar - Antioquia"],
["San antonio de Prado - Antioquia"],
["Arauca - Arauca"],
["Arauquita - Arauca"],
["Cravo Norte - Arauca"],
["Fortul - Arauca"],
["Puerto Rondón - Arauca"],
["Saravena - Arauca"],
["Tame - Arauca"],
["Panamá - Arauca"],
["Barranquilla - Atlantico"],
["Baranoa - Atlantico"],
["Campo de la Cruz - Atlantico"],
["Candelaria - Atlantico"],
["Galapa - Atlantico"],
["Juan de Acosta - Atlantico"],
["Luruaco - Atlantico"],
["Malambo - Atlantico"],
["Manatí - Atlantico"],
["Palmar de Varela - Atlantico"],
["Piojó - Atlantico"],
["Polonuevo - Atlantico"],
["Ponedera - Atlantico"],
["Puerto Colombia - Atlantico"],
["Repelón - Atlantico"],
["Sabanagrande - Atlantico"],
["Sabanalarga - Atlantico"],
["Santa Lucía - Atlantico"],
["Santo Tomás - Atlantico"],
["Soledad - Atlantico"],
["Suán - Atlantico"],
["Tubará - Atlantico"],
["Usiacurí - Atlantico"],
["Puerto Giraldo - Atlantico"],
["Caracoli - Atlantico"],
["Campeche - Atlantico"],
["Salgar - Atlantico"],
["Santo tomas - Atlantico"],
["Granvia - Atlantico"],
["Manouti - Atlantico"],
["Luban - Atlantico"],
["Isabel Lopez - Atlantico"],
["Concorde - Atlantico"],
["Achi - Bolivar"],
["Altos del Rosario - Bolivar"],
["Arenal del Sur - Bolivar"],
["Arjona - Bolivar"],
["Arroyo Hondo - Bolivar"],
["Barranco de Loba - Bolivar"],
["Calamar - Bolivar"],
["Cantagallo - Bolivar"],
["Carmen de Bolí­var - Bolivar"],
["Cartagena de Indias - Bolivar"],
["Cicuco - Bolivar"],
["Clemencia - Bolivar"],
["Córdoba - Bolivar"],
["El Guamo - Bolivar"],
["El Peñón - Bolivar"],
["Hatillo de Loba - Bolivar"],
["Magangue - Bolivar"],
["Mahates - Bolivar"],
["Margarita - Bolivar"],
["Maria La Baja - Bolivar"],
["Montecristo - Bolivar"],
["Morales - Bolivar"],
["Pinillos - Bolivar"],
["Regidor - Bolivar"],
["Rio Viejo - Bolivar"],
["San Cristobal - Bolivar"],
["San Estanislao - Bolivar"],
["San Fernando - Bolivar"],
["San Jacinto - Bolivar"],
["San Jacinto del Cauca - Bolivar"],
["San Juan Nepomuceno - Bolivar"],
["San Marían de Loba - Bolivar"],
["San Pablo - Bolivar"],
["Santa Catalina - Bolivar"],
["Santa Cruz de Mompós - Bolivar"],
["Santa Rosa - Bolivar"],
["Santa Rosa del Sur - Bolivar"],
["Simiti - Bolivar"],
["Soplaviento - Bolivar"],
["Talaigua Nuevo - Bolivar"],
["Tiquisio - Bolivar"],
["Turbaco - Bolivar"],
["Turbana - Bolivar"],
["Villanueva - Bolivar"],
["Zambrano - Bolivar"],
["Mompos - Bolivar"],
["Baru - Bolivar"],
["Bayunca - Bolivar"],
["Pasacaballo - Bolivar"],
["La Boquilla - Bolivar"],
["Piedra - Bolivar"],
["Cascajal - Bolivar"],
["Santa Rosa de Lima - Bolivar"],
["Malagana - Bolivar"],
["Santa Isabel - Bolivar"],
["Almeida  - Boyaca"],
["Aquitania  - Boyaca"],
["Arcabuco  - Boyaca"],
["Belén  - Boyaca"],
["Berbeo  - Boyaca"],
["Beteitiva  - Boyaca"],
["Boavita  - Boyaca"],
["Boyacá - Boyaca"],
["Briceño  - Boyaca"],
["Buenavista  - Boyaca"],
["Busbanzá - Boyaca"],
["Caldas  - Boyaca"],
["Campohermoso  - Boyaca"],
["Cerinza  - Boyaca"],
["Chinavita  - Boyaca"],
["Chiquinquirá - Boyaca"],
["Chiscas  - Boyaca"],
["Chiscas  - Boyaca"],
["Chita  - Boyaca"],
["Chitaraque  - Boyaca"],
["Chivor  - Boyaca"],
["Ciénega  - Boyaca"],
["Cómbita  - Boyaca"],
["Coper  - Boyaca"],
["Corrales  - Boyaca"],
["Covarachí­a  - Boyaca"],
["Cubará - Boyaca"],
["Cucaita  - Boyaca"],
["Cuitiva  - Boyaca"],
["Duitama  - Boyaca"],
["El Cocuy  - Boyaca"],
["El Cocuy  - Boyaca"],
["El Espino  - Boyaca"],
["El Espino  - Boyaca"],
["Firavitoba  - Boyaca"],
["Floresta  - Boyaca"],
["Gachantivá - Boyaca"],
["Gámeza  - Boyaca"],
["Garagoa  - Boyaca"],
["Guacamayas  - Boyaca"],
["Guacamayas  - Boyaca"],
["Guateque  - Boyaca"],
["Guayatá - Boyaca"],
["Guicán  - Boyaca"],
["Guicán  - Boyaca"],
["Iza  - Boyaca"],
["Jenesano  - Boyaca"],
["Jericó - Boyaca"],
["La Capilla  - Boyaca"],
["La Uvita  - Boyaca"],
["La Victoria  - Boyaca"],
["Labranzagrande  - Boyaca"],
["Macanal  - Boyaca"],
["Maripí - Boyaca"],
["Miraflores  - Boyaca"],
["Mongua  - Boyaca"],
["Monguí - Boyaca"],
["Moniquirá - Boyaca"],
["Muzo  - Boyaca"],
["Nobsa  - Boyaca"],
["Nuevo Colón  - Boyaca"],
["Oicata  - Boyaca"],
["Otanche  - Boyaca"],
["Pachavita  - Boyaca"],
["Páez  - Boyaca"],
["Paipa  - Boyaca"],
["Pajarito  - Boyaca"],
["Panqueba  - Boyaca"],
["Pauna  - Boyaca"],
["Paya  - Boyaca"],
["Paz de Río  - Boyaca"],
["Pesca  - Boyaca"],
["Pisba  - Boyaca"],
["Puerto Boyacá - Boyaca"],
["Quipama  - Boyaca"],
["Ramiriquí - Boyaca"],
["Ráquira  - Boyaca"],
["Rondón  - Boyaca"],
["Saboyá - Boyaca"],
["Sáchica  - Boyaca"],
["Samacá - Boyaca"],
["San Eduardo  - Boyaca"],
["San José de Pare  - Boyaca"],
["San Luis de Gaceno  - Boyaca"],
["San Mateo  - Boyaca"],
["San Miguel de Sema  - Boyaca"],
["San Pablo de Borbur  - Boyaca"],
["Santa María  - Boyaca"],
["Santa Rosa de Viterbo  - Boyaca"],
["Santa Sofía  - Boyaca"],
["Santana  - Boyaca"],
["Sativanorte  - Boyaca"],
["Sativasur  - Boyaca"],
["Siachoque  - Boyaca"],
["Soatá - Boyaca"],
["Socha  - Boyaca"],
["Socotá - Boyaca"],
["Sogamoso  - Boyaca"],
["Somondoco  - Boyaca"],
["Sora  - Boyaca"],
["Soracá - Boyaca"],
["Sotaquirá - Boyaca"],
["Susacón  - Boyaca"],
["Sutamarchán  - Boyaca"],
["Sutatenza  - Boyaca"],
["Tasco  - Boyaca"],
["Tenza  - Boyaca"],
["Tibaná - Boyaca"],
["Tibasosa  - Boyaca"],
["Tinjacá - Boyaca"],
["Tipacoque  - Boyaca"],
["Toca  - Boyaca"],
["Toguí - Boyaca"],
["Tópaga  - Boyaca"],
["Tota  - Boyaca"],
["Tunja - Boyaca"],
["Tununguá - Boyaca"],
["Turmequé - Boyaca"],
["Tuta  - Boyaca"],
["Tutasá - Boyaca"],
["Úmbita  - Boyaca"],
["Ventaquemada  - Boyaca"],
["Villa de Leyva  - Boyaca"],
["Viracachá - Boyaca"],
["Zetaquirá - Boyaca"],
["Simijaca - Boyaca"],
["Chivatá - Boyaca"],
["Motavita - Boyaca"],
["Aguadas - Caldas"],
["Anserma - Caldas"],
["Aranzazu - Caldas"],
["Belalcázar - Caldas"],
["Chinchiná - Caldas"],
["Filadelfia - Caldas"],
["La Dorada - Caldas"],
["La Merced - Caldas"],
["Manizales - Caldas"],
["Manzanares - Caldas"],
["Marmato - Caldas"],
["Marquetalia - Caldas"],
["Marulanda - Caldas"],
["Neira - Caldas"],
["Norcasia - Caldas"],
["Pácora - Caldas"],
["Palestina - Caldas"],
["Pensilvania - Caldas"],
["Riosucio - Caldas"],
["Risaralda - Caldas"],
["Salamina - Caldas"],
["Samaná - Caldas"],
["San José - Caldas"],
["Supía - Caldas"],
["Victoria - Caldas"],
["Villamaría - Caldas"],
["Viterbo - Caldas"],
["Arauca - Caldas"],
["Guarinocito - Caldas"],
["Albania - Caqueta"],
["Belén de los Andaquies - Caqueta"],
["Cartagena del Chairá - Caqueta"],
["Curillo - Caqueta"],
["El Doncello - Caqueta"],
["El Paujil - Caqueta"],
["Florencia - Caqueta"],
["La Montañita - Caqueta"],
["Milán - Caqueta"],
["Morelia - Caqueta"],
["Puerto Rico - Caqueta"],
["San José del Fragua - Caqueta"],
["San Vicente del Caguán - Caqueta"],
["Solano - Caqueta"],
["Solita - Caqueta"],
["Valparaíso - Caqueta"],
["Aguazul - Casanare"],
["Chámeza - Casanare"],
["Hato Corozal - Casanare"],
["La Salina - Casanare"],
["Maní - Casanare"],
["Monterrey - Casanare"],
["Nunchía - Casanare"],
["Orocué - Casanare"],
["Paz de Ariporo - Casanare"],
["Pore - Casanare"],
["Recetor - Casanare"],
["Sabanalarga - Casanare"],
["Sácama - Casanare"],
["San Luis de Palenque - Casanare"],
["Támara - Casanare"],
["Tauramena - Casanare"],
["Trinidad - Casanare"],
["Villanueva - Casanare"],
["Yopal - Casanare"],
["Chaparrera - Casanare"],
["Almaguer - Cauca"],
["Argelia - Cauca"],
["Balboa - Cauca"],
["Bolívar - Cauca"],
["Buenos Aires - Cauca"],
["Cajibío - Cauca"],
["Caldono - Cauca"],
["Caloto - Cauca"],
["Corinto - Cauca"],
["El Tambo - Cauca"],
["Guapi - Cauca"],
["Inzá - Cauca"],
["Jambaló - Cauca"],
["La Sierra - Cauca"],
["La Vega - Cauca"],
["López - Cauca"],
["Mercaderes - Cauca"],
["Miranda - Cauca"],
["Morales - Cauca"],
["Padilla - Cauca"],
["Páez - Cauca"],
["Patía - Cauca"],
["Piamonte - Cauca"],
["Piendamó - Cauca"],
["Popayán - Cauca"],
["Puerto Tejada - Cauca"],
["Puracé - Cauca"],
["Rosas - Cauca"],
["San Sebastián - Cauca"],
["Santa Rosa - Cauca"],
["Santander de Quilichao - Cauca"],
["Silvia - Cauca"],
["Sotará - Cauca"],
["Suárez - Cauca"],
["Timbí­o - Cauca"],
["Timbiquí - Cauca"],
["Toribío - Cauca"],
["Totoro - Cauca"],
["Timba - Cauca"],
["Villa Rica - Cauca"],
["Piedrasentada - Cauca"],
["Rio Blanco - Cauca"],
["Mondomo - Cauca"],
["El Bordo - Cauca"],
["Guachicono - Cauca"],
["Aguachica - Cesar"],
["Agustin Codazzi - Cesar"],
["Astrea - Cesar"],
["Becerril - Cesar"],
["Bosconia - Cesar"],
["Chimichagua - Cesar"],
["Chiriguaná - Cesar"],
["Curumaní - Cesar"],
["El Copey - Cesar"],
["El Paso - Cesar"],
["Galeras - Cesar"],
["Gamarra - Cesar"],
["Gonzalez - Cesar"],
["La Gloria - Cesar"],
["La Jagua de Ibirico - Cesar"],
["La Paz - Cesar"],
["Manaure Balcón del Cesar - Cesar"],
["Pailitas - Cesar"],
["Pelaya - Cesar"],
["Pueblo Bello - Cesar"],
["Río de Oro - Cesar"],
["San Alberto - Cesar"],
["San Diego - Cesar"],
["San Martín - Cesar"],
["Tamalameque - Cesar"],
["Valledupar - Cesar"],
["La Loma - Cesar"],
["Villanueva - Cesar - Cesar"],
["Patilla - Cesar"],
["San Roque - Cesar"],
["San Jos de Oriente - Cesar"],
["Mandinguilla - Cesar"],
["Media Luna Cesar - Cesar"],
["Casacara - Cesar"],
["Ayacucho - Cesar"],
["Guacoche - Cesar"],
["Besotes - Cesar"],
["La mata - Cesar"],
["El burro - Cesar"],
["Las vegas - Cesar"],
["Zapatosa - Cesar"],
["Saloa - Cesar"],
["Acandí - Choco"],
["Alto Baudó - Choco"],
["Atrato - Choco"],
["Bagadó - Choco"],
["Bahí­a Solano - Choco"],
["Bajo Baudó - Choco"],
["Bojayá - Choco"],
["Cantón de San Pablo - Choco"],
["Carmen del Atrato - Choco"],
["Condoto - Choco"],
["Itsmina - Choco"],
["Juradó - Choco"],
["Litoral de San Juan - Choco"],
["Lloró - Choco"],
["Medio Atrato - Choco"],
["Medio San Juan - Choco"],
["Nóvita - Choco"],
["Nuquí - Choco"],
["Quibdó - Choco"],
["Riosucio - Choco"],
["San José del Palmar - Choco"],
["Sipí - Choco"],
["Tadó - Choco"],
["Unguía - Choco"],
["Unión Panamericana - Choco"],
["Belen de Bajira - Choco"],
["Carmen del Darien - Choco"],
["Certegui - Choco"],
["Medio Baud   (Puerto Meluk) - Choco"],
["Ayapel - Cordoba"],
["Buenavista - Cordoba"],
["Canalete - Cordoba"],
["Cerete - Cordoba"],
["Chima - Cordoba"],
["Chinú - Cordoba"],
["Ciénaga de Oro - Cordoba"],
["Cotorra - Cordoba"],
["La Apartada - Cordoba"],
["Lorica - Cordoba"],
["Los Córdobas - Cordoba"],
["Momil - Cordoba"],
["Monitos - Cordoba"],
["Montelíbano - Cordoba"],
["Monterí­a - Cordoba"],
["Planeta Rica - Cordoba"],
["Pueblo Nuevo - Cordoba"],
["Puerto Escondido - Cordoba"],
["Puerto Libertador - Cordoba"],
["Purísima - Cordoba"],
["Sahagún - Cordoba"],
["San Andrés de Sotavento - Cordoba"],
["San Antero - Cordoba"],
["San Bernardo del Viento - Cordoba"],
["San Carlos - Cordoba"],
["San Pelayo - Cordoba"],
["Tierralta - Cordoba"],
["Tuchín - Cordoba"],
["Valencia - Cordoba"],
["Carrillo - Cordoba"],
["Purisima - Cordoba"],
["Chino - Cordoba"],
["Guaimarito - Cordoba"],
["La ye - Cordoba"],
["Las lomas - Cordoba"],
["Las manuelitas - Cordoba"],
["Nueva estacion - Cordoba"],
["Rancheria - Cordoba"],
["Viajano - Cordoba"],
["Agua de Dios  - Cundinamarca"],
["Albán  - Cundinamarca"],
["Anapoima  - Cundinamarca"],
["Anolaima  - Cundinamarca"],
["Apulo  - Cundinamarca"],
["Arbelaéz  - Cundinamarca"],
["Beltrán  - Cundinamarca"],
["Bituima  - Cundinamarca"],
["Bojacá  - Cundinamarca"],
["Cabrera  - Cundinamarca"],
["Cabrera  - Cundinamarca"],
["Cachipay  - Cundinamarca"],
["Cajicá - Cundinamarca"],
["Caparrapí - Cundinamarca"],
["Cáqueza (Capital)  - Cundinamarca"],
["Carmen de Carupa  - Cundinamarca"],
["Chaguaní - Cundinamarca"],
["Chí­a  - Cundinamarca"],
["Chipaque  - Cundinamarca"],
["Choachí - Cundinamarca"],
["Chocontá - Cundinamarca"],
["Cogua  - Cundinamarca"],
["Cota  - Cundinamarca"],
["Cucunubá - Cundinamarca"],
["El Colegio  - Cundinamarca"],
["El Peñón  - Cundinamarca"],
["El Rosal  - Cundinamarca"],
["Facatativá - Cundinamarca"],
["Fómeque  - Cundinamarca"],
["Fosca  - Cundinamarca"],
["Funza  - Cundinamarca"],
["Fúquene  - Cundinamarca"],
["Fusagasugá - Cundinamarca"],
["Gachalá - Cundinamarca"],
["Gachancipá - Cundinamarca"],
["Gachetá (Capital)  - Cundinamarca"],
["Gama  - Cundinamarca"],
["Girardot (Capital)  - Cundinamarca"],
["Granada  - Cundinamarca"],
["Guachetá - Cundinamarca"],
["Guaduas (Capital)  - Cundinamarca"],
["Guasca  - Cundinamarca"],
["Guataquí - Cundinamarca"],
["Guatavita  - Cundinamarca"],
["Guayabal de Sí­quima  - Cundinamarca"],
["Guayabetal  - Cundinamarca"],
["Gutiérrez  - Cundinamarca"],
["Jerusalén  - Cundinamarca"],
["Junín  - Cundinamarca"],
["La Calera  - Cundinamarca"],
["La Mesa - Cundinamarca"],
["La Palma  - Cundinamarca"],
["La Peña  - Cundinamarca"],
["Lenguazaque  - Cundinamarca"],
["Machetá - Cundinamarca"],
["Madrid  - Cundinamarca"],
["Manta  - Cundinamarca"],
["Medina (Capital)  - Cundinamarca"],
["Mosquera  - Cundinamarca"],
["Nariño  - Cundinamarca"],
["Nemocón  - Cundinamarca"],
["Nilo  - Cundinamarca"],
["Nimaima  - Cundinamarca"],
["Nocaima  - Cundinamarca"],
["Pacho (Capital)  - Cundinamarca"],
["Paime  - Cundinamarca"],
["Pandi  - Cundinamarca"],
["Paratebueno  - Cundinamarca"],
["Pasca  - Cundinamarca"],
["Puerto Salgar  - Cundinamarca"],
["Pulí - Cundinamarca"],
["Quebradanegra  - Cundinamarca"],
["Quetame  - Cundinamarca"],
["Quipile  - Cundinamarca"],
["Ricaurte  - Cundinamarca"],
["San Antonio del Tequendama  - Cundinamarca"],
["San Bernardo  - Cundinamarca"],
["San Cayetano  - Cundinamarca"],
["San Francisco  - Cundinamarca"],
["San Juan de Rioseco (Capital)  - Cundinamarca"],
["Sasaima  - Cundinamarca"],
["Sesquilé - Cundinamarca"],
["Sibaté - Cundinamarca"],
["Silvania  - Cundinamarca"],
["Simijaca  - Cundinamarca"],
["Soacha - Cundinamarca"],
["Sopó - Cundinamarca"],
["Subachoque  - Cundinamarca"],
["Suesca  - Cundinamarca"],
["Supatá - Cundinamarca"],
["Susa  - Cundinamarca"],
["Sutatausa  - Cundinamarca"],
["Tabio  - Cundinamarca"],
["Tausa  - Cundinamarca"],
["Tena  - Cundinamarca"],
["Tenjo  - Cundinamarca"],
["Tibacuy  - Cundinamarca"],
["Tibirita  - Cundinamarca"],
["Tocaima  - Cundinamarca"],
["Tocancipá - Cundinamarca"],
["Topaipí - Cundinamarca"],
["Ubalá - Cundinamarca"],
["Ubaque  - Cundinamarca"],
["Ubaté - Cundinamarca"],
["Une  - Cundinamarca"],
["Útica  - Cundinamarca"],
["Venecia - Cundinamarca"],
["Vergara  - Cundinamarca"],
["Vianí - Cundinamarca"],
["Villagómez  - Cundinamarca"],
["Villapinzón  - Cundinamarca"],
["Villeta (Capital)  - Cundinamarca"],
["Viotá - Cundinamarca"],
["Yacopí - Cundinamarca"],
["Zipacón  - Cundinamarca"],
["Zipaquirá - Cundinamarca"],
["Bogotá - Cundinamarca"],
["Subia - Cundinamarca"],
["Pradilla - Cundinamarca"],
["Saname - Cundinamarca"],
["La Sierra - Cundinamarca"],
["La Vega - Cundinamarca"],
["La Paz  - Cundinamarca"],
["Briceno - Cundinamarca"],
["Chinauta - Cundinamarca"],
["Iní­rida - Guainia"],
["Calamar - Guaviare"],
["El Retorno - Guaviare"],
["Miraflores - Guaviare"],
["Morichal - Guaviare"],
["San José del Guaviare - Guaviare"],
["Acevedo - Huila"],
["Agrado - Huila"],
["Aipe - Huila"],
["Algeciras - Huila"],
["Altamira - Huila"],
["Baraya - Huila"],
["Campoalegre - Huila"],
["Colombia - Huila"],
["Elí­as - Huila"],
["Garzón - Huila"],
["Gigante - Huila"],
["Guadalupe - Huila"],
["Hobo - Huila"],
["Iquira - Huila"],
["Isnos - Huila"],
["La Argentina - Huila"],
["La Plata - Huila"],
["Nátaga - Huila"],
["Neiva - Huila"],
["Oporapa - Huila"],
["Paicol - Huila"],
["Palermo - Huila"],
["Palestina - Huila"],
["Pital - Huila"],
["Pitalito - Huila"],
["Rivera - Huila"],
["Saladoblanco - Huila"],
["San Agustí­n - Huila"],
["Santa Marí­a - Huila"],
["Suaza - Huila"],
["Tarqui - Huila"],
["Tello - Huila"],
["Teruel - Huila"],
["Timana - Huila"],
["Tesalia - Huila"],
["Villavieja - Huila"],
["Yaguará - Huila"],
["Zuluaga - Huila"],
["San Adolfo - Huila"],
["San Jose de Isnos - Huila"],
["La Estrella  - Huila"],
["Mira Flores - Huila"],
["Bruselas - Huila"],
["Belen - Huila"],
["Guacacallo - Huila"],
["Albania - La Guajira"],
["Barrancas - La Guajira"],
["Dibulla - La Guajira"],
["Distracción - La Guajira"],
["El Molino - La Guajira"],
["Fonseca - La Guajira"],
["Hatonuevo - La Guajira"],
["La Jagua del Pilar - La Guajira"],
["Maicao - La Guajira"],
["Manaure - La Guajira"],
["Riohacha - La Guajira"],
["San Juan del Cesar - La Guajira"],
["Uribia - La Guajira"],
["Urumita - La Guajira"],
["Villanueva - La Guajira"],
["Palomino - La Guajira"],
["Papayal - La Guajira"],
["Paraguachon - La Guajira"],
["Rio Ancho - La Guajira"],
["Puerto Bolivar - La Guajira"],
["Puente Bomba - La Guajira"],
["Mingueo - La Guajira"],
["Nazareth - La Guajira"],
["El Pajaro - La Guajira"],
["Algarrobo - Magdalena"],
["Aracataca - Magdalena"],
["Ariguaní - Magdalena"],
["Cerro de San Antonio - Magdalena"],
["Chivolo - Magdalena"],
["Ciénaga - Magdalena"],
["El Banco - Magdalena"],
["El Piñón - Magdalena"],
["El Retén - Magdalena"],
["Fundación - Magdalena"],
["Guamal - Magdalena"],
["Nueva Granada - Magdalena"],
["Pedraza - Magdalena"],
["Pijiño del Carmen - Magdalena"],
["Pivijay - Magdalena"],
["Plato - Magdalena"],
["Pueblo Viejo - Magdalena"],
["Remolino - Magdalena"],
["Sabanas de San Angel - Magdalena"],
["Salamina - Magdalena"],
["San Sebastián de Buenavista - Magdalena"],
["San Zenón - Magdalena"],
["Santa Ana - Magdalena"],
["Santa Barbara - Magdalena"],
["Santa Marta - Magdalena"],
["Sitionuevo - Magdalena"],
["Tenerife - Magdalena"],
["Zapayán - Magdalena"],
["Zona Bananera  - Magdalena"],
["El Dificil - Magdalena"],
["Santa Rosalia - Magdalena"],
["Sevilla - Magdalena"],
["Tasajeras - Magdalena"],
["Tucurinca - Magdalena"],
["Varela - Magdalena"],
["Palermo - Magdalena"],
["Rio Frio - Magdalena"],
["San Pedro de la Sierra - Magdalena"],
["Santa Barbara de Pinto - Magdalena"],
["La Gran Via - Magdalena"],
["Los Andes - Magdalena"],
["Marquetalia - Magdalena"],
["Monterrubio - Magdalena"],
["Bonda - Magdalena"],
["Buritaca - Magdalena"],
["Concordia - Magdalena"],
["El Palmor - Magdalena"],
["El pueblito - Magdalena"],
["Gaira - Magdalena"],
["Guacamayal - Magdalena"],
["Guachaca - Magdalena"],
["Orihueca - Magdalena"],
["Acacías - Meta"],
["Barranca de Upía - Meta"],
["Cabuyaro - Meta"],
["Castilla la Nueva - Meta"],
["Cubarral - Meta"],
["Cumaral - Meta"],
["El Calvario - Meta"],
["El Castillo - Meta"],
["El Dorado - Meta"],
["Fuente de Oro - Meta"],
["Granada - Meta"],
["Guamal - Meta"],
["La Macarena - Meta"],
["La Uribe - Meta"],
["Lejanías - Meta"],
["Mapiripán - Meta"],
["Mesetas - Meta"],
["Puerto Concordia - Meta"],
["Puerto Gaitán - Meta"],
["Puerto Lleras - Meta"],
["Puerto López - Meta"],
["Puerto Rico - Meta"],
["Restrepo - Meta"],
["San Carlos Guaroa - Meta"],
["San Juan de Arama - Meta"],
["San Juanito - Meta"],
["San Martí­n - Meta"],
["Villavicencio - Meta"],
["Vista Hermosa - Meta"],
["Paratebueno - Meta"],
["Medina - Meta"],
["Albán - Narino"],
["Aldana  - Narino"],
["Ancuyá - Narino"],
["Arboleda - Narino"],
["Barbacoas - Narino"],
["Belén  - Narino"],
["Buesaco  - Narino"],
["Chachaguí - Narino"],
["Colón - Narino"],
["Consacá - Narino"],
["Contadero  - Narino"],
["Córdoba  - Narino"],
["Cuaspud - Narino"],
["Cumbal  - Narino"],
["Cumbitara  - Narino"],
["El Charco - Narino"],
["El Rosario  - Narino"],
["El Tablón  - Narino"],
["El Tambo  - Narino"],
["Francisco Pizarro  - Narino"],
["Funes  - Narino"],
["Guachucal  - Narino"],
["Guaitarilla  - Narino"],
["Gualmatán  - Narino"],
["Iles  - Narino"],
["Iles  - Narino"],
["Imues  - Narino"],
["Imúes  - Narino"],
["Ipiales  - Narino"],
["La Cruz  - Narino"],
["La Florida  - Narino"],
["La Llanada  - Narino"],
["La Tola  - Narino"],
["La Unión  - Narino"],
["Leiva  - Narino"],
["Linares  - Narino"],
["Los Andes - Narino"],
["Maguí - Narino"],
["Mallama - Narino"],
["Mosquera  - Narino"],
["Nariño  - Narino"],
["Olaya  - Narino"],
["Ospina  - Narino"],
["Pasto  - Narino"],
["Policarpa  - Narino"],
["Potosí - Narino"],
["Providencia  - Narino"],
["Puerres  - Narino"],
["Pupiales  - Narino"],
["Ricaurte  - Narino"],
["Roberto Payán - Narino"],
["Samaniego  - Narino"],
["San Bernardo  - Narino"],
["San Lorenzo  - Narino"],
["San Pablo  - Narino"],
["San Pedro de Cartago  - Narino"],
["Sandoná - Narino"],
["Santa Bárbara - Narino"],
["Santacruz - Narino"],
["Sapuyes  - Narino"],
["Taminango  - Narino"],
["Tangua  - Narino"],
["Tumaco  - Narino"],
["Túquerres  - Narino"],
["Yacuanquer  - Narino"],
["Llorente - Narino"],
["Piedrancha - Narino"],
["El Encano - Narino"],
["El Espino - Narino"],
["Abrego  - Norte de Santander"],
["Arboledaz  - Norte de Santander"],
["Bochalema  - Norte de Santander"],
["Bucarasica  - Norte de Santander"],
["Cáchira  - Norte de Santander"],
["Cacota  - Norte de Santander"],
["Chinácota  - Norte de Santander"],
["Chitaga  - Norte de Santander"],
["Convención  - Norte de Santander"],
["Cúcuta  - Norte de Santander"],
["Cucutillas  - Norte de Santander"],
["Duranía  - Norte de Santander"],
["El Carmen  - Norte de Santander"],
["El Tarra  - Norte de Santander"],
["El Zulia  - Norte de Santander"],
["Gramalote  - Norte de Santander"],
["Hacari  - Norte de Santander"],
["Herrán  - Norte de Santander"],
["La Esperanza  - Norte de Santander"],
["La Playa  - Norte de Santander"],
["Labateca  - Norte de Santander"],
["Los Patios  - Norte de Santander"],
["Lourdes  - Norte de Santander"],
["Mutiscua  - Norte de Santander"],
["Ocaña  - Norte de Santander"],
["Pamplona  - Norte de Santander"],
["Pamplonita  - Norte de Santander"],
["Puerto Santander  - Norte de Santander"],
["Ragonvalia  - Norte de Santander"],
["Salazar de Las Palmas  - Norte de Santander"],
["San Calixto  - Norte de Santander"],
["San Cayetano  - Norte de Santander"],
["Santiago  - Norte de Santander"],
["Sardinata  - Norte de Santander"],
["Silos  - Norte de Santander"],
["Teorama  - Norte de Santander"],
["Tibú - Norte de Santander"],
["Toledo - Norte de Santander"],
["Villa Caro  - Norte de Santander"],
["Villa del Rosario  - Norte de Santander"],
["Agua Clara - Norte de Santander"],
["Cornejo - Norte de Santander"],
["La Donjuana - Norte de Santander"],
["Colón - Putumayo"],
["Mocoa - Putumayo"],
["Orito - Putumayo"],
["Puerto Asís - Putumayo"],
["Puerto Caicedo - Putumayo"],
["Puerto Guzmán - Putumayo"],
["Puerto Leguizamo - Putumayo"],
["San francisco - Putumayo"],
["San Miguel - Putumayo"],
["Santiago - Putumayo"],
["Sibundoy - Putumayo"],
["Valle del Guamez - Putumayo"],
["VillaGarzón - Putumayo"],
["La Hormiga - Putumayo"],
["Santana  - Putumayo"],
["La Dorada - Putumayo"],
["Armenia - Quindio"],
["Buenavista - Quindio"],
["Calarcá - Quindio"],
["Circasia - Quindio"],
["Córdoba - Quindio"],
["Filandia - Quindio"],
["Génova - Quindio"],
["La Tebaida - Quindio"],
["Montenegro - Quindio"],
["Pijao - Quindio"],
["Quimbaya - Quindio"],
["Salento - Quindio"],
["Alcalá - Quindio"],
["Caicedonia - Quindio"],
["Cartago - Quindio"],
["Obando - Quindio"],
["Zarzal - Quindio"],
["Pueblo Tapao - Quindio"],
["Barcelona - Quindio"],
["Apía - Risaralda"],
["Balboa - Risaralda"],
["Belén de Umbrí­a - Risaralda"],
["Dosquebradas - Risaralda"],
["Guatica - Risaralda"],
["La Celia - Risaralda"],
["La Virginia - Risaralda"],
["Marsella - Risaralda"],
["Mistrató - Risaralda"],
["Pereira - Risaralda"],
["Pueblo Rico - Risaralda"],
["Quinchía - Risaralda"],
["Santa Rosa de Cabal - Risaralda"],
["Santuario - Risaralda"],
["Belalcazar - Risaralda"],
["Cuba - Risaralda"],
["Belalcazar - Risaralda"],
["Providencia - San Andres y Providencia"],
["San Andrés - San Andres y Providencia"],
["Aguada  - Santander"],
["Albania  - Santander"],
["Aratoca  - Santander"],
["Barbosa  - Santander"],
["Barichara  - Santander"],
["Barrancabermeja  - Santander"],
["Betulia  - Santander"],
["Bolívar  - Santander"],
["Bucaramanga  - Santander"],
["Cabrera  - Santander"],
["California  - Santander"],
["Capitanejo  - Santander"],
["Carcasí - Santander"],
["Cepitá - Santander"],
["Cerrito  - Santander"],
["Charalá - Santander"],
["Charta  - Santander"],
["Chima  - Santander"],
["Chipatá - Santander"],
["Cimitarra  - Santander"],
["Concepción  - Santander"],
["Confines  - Santander"],
["Contratación  - Santander"],
["Coromoro  - Santander"],
["Curití - Santander"],
["El Carmen  - Santander"],
["El Guacamayo  - Santander"],
["El Peñón  - Santander"],
["El Playón  - Santander"],
["Encino  - Santander"],
["Enciso  - Santander"],
["Florián  - Santander"],
["Floridablanca  - Santander"],
["Galán  - Santander"],
["Gámbita  - Santander"],
["Girón  - Santander"],
["Guaca  - Santander"],
["Guadalupe  - Santander"],
["Guapotá - Santander"],
["Guavatá - Santander"],
["Guepsa  - Santander"],
["Hato  - Santander"],
["Jesús Marí­a  - Santander"],
["Jordán  - Santander"],
["La Belleza  - Santander"],
["La Paz  - Santander"],
["Landázuri  - Santander"],
["Lebrija  - Santander"],
["Los Santos  - Santander"],
["Macaravita  - Santander"],
["Málaga  - Santander"],
["Matanza  - Santander"],
["Mogotes  - Santander"],
["Molagavita  - Santander"],
["Ocamonte  - Santander"],
["Oiba  - Santander"],
["Onzaga  - Santander"],
["Palmar  - Santander"],
["Palmas del Socorro  - Santander"],
["Páramo  - Santander"],
["Piedecuesta  - Santander"],
["Pinchote  - Santander"],
["Puente Nacional  - Santander"],
["Puerto Parra  - Santander"],
["Puerto Wilches  - Santander"],
["Rionegro  - Santander"],
["Sabana de Torres  - Santander"],
["San Andrés  - Santander"],
["San Benito  - Santander"],
["San Gil  - Santander"],
["San Joaquín  - Santander"],
["San Jose de Miranda  - Santander"],
["San Miguel  - Santander"],
["San Vicente  - Santander"],
["Santa Bárbara  - Santander"],
["Santa Helena del Opón  - Santander"],
["Simacota  - Santander"],
["Socorro  - Santander"],
["Suaita  - Santander"],
["Sucre  - Santander"],
["Suratá - Santander"],
["Tona  - Santander"],
["Valle de San José - Santander"],
["Vélez  - Santander"],
["Vetas  - Santander"],
["Villanueva  - Santander"],
["Zapatoca  - Santander"],
["Puente Sogamoso - Santander"],
["La Mesa de los Santos - Santander"],
["Buenavista - Sucre"],
["Caimito - Sucre"],
["Chalán - Sucre"],
["Coloso - Sucre"],
["Corozal - Sucre"],
["Coveñas - Sucre"],
["Galeras - Sucre"],
["Guaranda - Sucre"],
["La Unión - Sucre"],
["Los Palmitos - Sucre"],
["Majagual - Sucre"],
["Morroa - Sucre"],
["Ovejas - Sucre"],
["Palmito - Sucre"],
["Sampués - Sucre"],
["San Benito Abad - Sucre"],
["San Juan Betulia - Sucre"],
["San Marcos - Sucre"],
["San Onofre - Sucre"],
["San Pedro - Sucre"],
["Sincé - Sucre"],
["Sincelejo - Sucre"],
["Sucre - Sucre"],
["Tolú - Sucre"],
["Toluviejo - Sucre"],
["Santiago Apostol - Sucre"],
["Sabanas de Beltran - Sucre"],
["San Andres - Sucre"],
["La Sierpe - Sucre"],
["Martin Alonso - Sucre"],
["Albania - Sucre - Sucre"],
["Berrugas - Sucre"],
["Chinu - Sucre"],
["Chapinero - Sucre"],
["Granada - Sucre"],
["El Roble - Sucre"],
["Don Alonso - Sucre"],
["Chocho - Sucre"],
["Canutal - Sucre"],
["El bongo - Sucre"],
["El piñal - Sucre"],
["Chinolito - Sucre"],
["Macajan - Sucre"],
["Punta de piedra - Sucre"],
["Alpujarra - Tolima"],
["Alvarado - Tolima"],
["Ambalema - Tolima"],
["Anzoátequi - Tolima"],
["Armero/Guayabal - Tolima"],
["Ataco - Tolima"],
["Cajamarca - Tolima"],
["Carmen de Apicalá - Tolima"],
["Casabianca - Tolima"],
["Chaparral - Tolima"],
["Coello - Tolima"],
["Coyaima - Tolima"],
["Cunday - Tolima"],
["Dolores - Tolima"],
["Espinal - Tolima"],
["Falan - Tolima"],
["Flandes - Tolima"],
["Fresno - Tolima"],
["Guamo - Tolima"],
["Herveo - Tolima"],
["Honda - Tolima"],
["Ibagué - Tolima"],
["Icononzo - Tolima"],
["Lérida - Tolima"],
["Líbano - Tolima"],
["Mariquita - Tolima"],
["Melgar - Tolima"],
["Murillo - Tolima"],
["Natagaima - Tolima"],
["Ortega - Tolima"],
["Palocabildo - Tolima"],
["Piedras - Tolima"],
["Planadas - Tolima"],
["Prado - Tolima"],
["Purificación - Tolima"],
["Rioblanco - Tolima"],
["Roncesvalles - Tolima"],
["Rovira - Tolima"],
["Saldaña - Tolima"],
["San Antonio - Tolima"],
["San Luis - Tolima"],
["Santa Isabel - Tolima"],
["Suárez - Tolima"],
["Valle de San Juan - Tolima"],
["Venadillo - Tolima"],
["Villahermosa - Tolima"],
["Villarrica - Tolima"],
["Playa Rica - Tolima"],
["Andalucia - Valle del Cauca"],
["Ansermanuevo - Valle del Cauca"],
["Argelia - Valle del Cauca"],
["Bolivar - Valle del Cauca"],
["Buenaventura - Valle del Cauca"],
["Buga - Valle del Cauca"],
["Bugalagrande - Valle del Cauca"],
["Cali - Valle del Cauca"],
["Candelaria - Valle del Cauca"],
["Dagua - Valle del Cauca"],
["Darién - Valle del Cauca"],
["El Aguila - Valle del Cauca"],
["El Cairo - Valle del Cauca"],
["El Cerrito - Valle del Cauca"],
["El Dovio - Valle del Cauca"],
["Florida - Valle del Cauca"],
["Ginebra - Valle del Cauca"],
["Guacarí - Valle del Cauca"],
["Jamundí - Valle del Cauca"],
["La Cumbre - Valle del Cauca"],
["La Union/Valle - Valle del Cauca"],
["La Victoria - Valle del Cauca"],
["Palmira - Valle del Cauca"],
["Pradera - Valle del Cauca"],
["Restrepo - Valle del Cauca"],
["Riofrio - Valle del Cauca"],
["Roldanillo - Valle del Cauca"],
["San Pedro - Valle del Cauca"],
["Sevilla - Valle del Cauca - Valle del Cauca"],
["Toro - Valle del Cauca"],
["Trujillo - Valle del Cauca"],
["Tulua - Valle del Cauca"],
["Ulloa - Valle del Cauca"],
["Versalles - Valle del Cauca"],
["Yotoco - Valle del Cauca"],
["Yumbo - Valle del Cauca"],
["Venecia - Valle del Cauca"],
["Vijes  - Valle del Cauca"],
["Villagorgona - Valle del Cauca"],
["Potrerito - Valle del Cauca"],
["La Habana - Valle del Cauca"],
["Media Canoa  - Valle del Cauca"],
["Aguaclara - Valle del Cauca"],
["Ceilan - Valle del Cauca"],
["Costa Rica - Valle del Cauca"],
["El Placer - Valle del Cauca"],
["Cisneros - Valle del Cauca"],
["Robles - Valle del Cauca"],
["Rozo - Valle del Cauca"],
["Sabaletas - Valle del Cauca"],
["San Antonio de los Caballe - Valle del Cauca"],
["Puente Tierra - Valle del Cauca"],
["La Paila - Valle del Cauca"],
["Queremal - Valle del Cauca"],
["Quebrada Nueva - Valle del Cauca"],
["Vallejuelo - Valle del Cauca"],
["Carurú - Vaupes"],
["Mitú - Vaupes"],
["Taraira - Vaupes"],
["Cumaribo - Vichada"],
["La Primavera - Vichada"],
["Puerto Carreño - Vichada"],
["Santa Rosalía - Vichada"]]

hash_city = {first_name: "Medellin", 
	         last_name:  "Medellin",
             email:      "medellinn@medellin.com",     
             password:   "Medellin",
             status:    2
            }

ciudades.each do |ciudad|
	begin
	  temp_array = ciudad.first.split(" - ")
	  tmp_state = State.select('distinct id').find_by(name: temp_array[1])
	  City.create( name: temp_array[0], state_id: tmp_state.id, link_rewrite: temp_array[0].downcase, created_at: Time.now, updated_at: Time.now)
	rescue Exception => e
	  puts e.to_s
	  puts "************ciudades****************"
	  puts 	temp_array[1]
	  puts  temp_array[0]
	  puts  "***************************"
	end

end

params_use = hash_city

Offer.destroy_all

offers = [['Plan generico', Environment::TYPE[:planes][:generico], 0,0,0,0,0],
          ['Plan promocional', Environment::TYPE[:planes][:promocional], 0,0,10,10,10]]


offers.each do |name, type, precio1, precio2, trucks, extra, service|
	begin
	  Offer.create!( nombre: name, typeoffer: type, precio1: precio1, precio2: precio2, trucks: trucks, extra: extra, service: service)
	rescue Exception => e
	  puts "*************offers***************"
	  puts e.to_s
	  puts  "***************************"
	end
end

Customer.destroy_all

params_user = {first_name:   "daniel", 
	           last_name:    "punk4",
               email:        "danielpunk4@gmail.com",     
               password:     "danielpunk4@gmail.com",
               status:       1
              }

User.create!(params_user)
User.create!(params_use)

params_user = {first_name:   "admin", 
	           last_name:    "admin",
               email:        "admin@admin.com",     
               password:     "Admin_Camion",
               status:       1
              }

User.create!(params_user)



BrandTruck.destroy_all

marcas = ["AGRALE",
"AMPLE",
"ASIA",
"AUTOCAR",
"BAIC",
"BAW",
"CHANA",
"CHANGHE",
"CHERY",
"CHEVROLET",
"CITROEN",
"DAEWOO",
"DAIHATSU",
"DFAC",
"DFSK/DFM",
"DINA",
"DODGE",
"EUROSTAR D`LONG",
"FAW AMI",
"FIAT",
"FORD",
"FOTON",
"FREIGHTLINER",
"GAZ",
"GOLDEN DRAGON",
"GONOW",
"GREAT WALL MOTOR",
"HAFEI",
"HIGER",
"HINO",
"HYUNDAI",
"IFA",
"INTERNATIONAL",
"ISUZU",
"IVECO",
"JAC",
"JINBEI",
"JMC",
"JOYLONG",
"KAMAZ",
"KENWORTH",
"KIA",
"KRAZ",
"LAND ROVER",
"MACK",
"MAHINDRA",
"MARMON",
"MAXUS",
"MAZDA",
"MERCEDES BENZ",
"MITSUBISHI",
"MUDAN",
"NISSAN",
"NON PLUS ULTRA",
"OLTCIT",
"PAZ",
"PEGASSO",
"PETERBILT",
"PEUGEOT",
"RENAULT",
"RENNO",
"SAICWULING",
"SCANIA",
"SINOTRUK",
"SISU",
"SSANGYONG",
"STEYR",
"SUZUKI",
"T-KING",
"TATA",
"TMD",
"TOYOTA",
"VOLKSWAGEN",
"VOLVO",
"WESTERN STAR",
"XINKAI",
"YAXING",
"YUEJIN",
"YUTONG",
"ZHONGXING",
"ZNA"]


marcas.each do |name|
	begin
	  BrandTruck.create!(name: name, link_rewrite: name)
	rescue Exception => e
	  puts "************marcas****************"
      puts e.to_s
	  puts  "***************************"
	end
end